### ISSUE TITLE
打印输出的内容可以优化一下嘛

### ISSUE THREAD

**Issue by qieqie7** [jaluik/dot-log#1]

**Comment by qieqie7** [comment]
console.log('foo',foo)


console.log('foo: ', foo);
加入一些空格和冒号，可以吗

**Comment by jaluik** [comment]
可以， 我加个配置信息吧。 晚点我更新一下配置说明

**Comment by tree-white** [comment]
请问该功能实现了不，我习惯在log上面添加「=>」所以在默认生成的 `console.log('xxx',xxx)` 看着有点不习惯，希望可以实现自定义key后面的内容这样我就可以实现 `console.log('xxx=>',xxx)` 了

**Comment by jaluik** [comment]
> 请问该功能实现了不，我习惯在log上面添加「=>」所以在默认生成的 `console.log('xxx',xxx)` 看着有点不习惯，希望可以实现自定义key后面的内容这样我就可以实现 `console.log('xxx=>',xxx)` 了


已经实现了，在0.1.3版本增加了配置项，你可以在suffix中配置为：` =>`，就可以了。

ps： 想问一下你是从哪里了解到这个插件的？ @tree-white 


```json
  "dotLog.config": [
        {
            "trigger": "log", 
            "description": "quick console.log result",
            "format": "console.log",  
            "suffix": " =>",  
        }
    ]
```

**Comment by jaluik** [comment]
用0.1.3的最新版加一个配置项， suffix: " :" 就可以了  @qieqie7

**Comment by tree-white** [comment]
> 

好的感谢，从后盾人大叔那里了解到的
