### ISSUE TITLE
建议添加置顶xxx.log的提示顺序的功能

### ISSUE THREAD

**Issue by ccp-p** [jaluik/dot-log#10]
vue开发需要用到vetur，vetur又自带一个log提示，导致xxx.log的时候得得按下方向键再tab![image](https://github.com/jaluik/dot-log/assets/54465780/a54e4395-588c-4ec0-b232-172f0f7353d4)

**Comment by jaluik** [comment]
ok, i will try to fix this.

**Comment by jaluik** [comment]
这个我看了一下应该不是vetur提供的，应该是其他插件提供的， 如果你想要制定顺序提示，可以调整一下你的配置，把`.log`的触发改成其他的，比如想更新成这个`.clg`触发，可以更改配置成这样  @ccp-p 

```
 "dotLog.config": [
        {
            "trigger": "clg",
            "description": "quick console.log result",
            "format": "console.log",
        }
]
```

**Comment by ccp-p** [comment]
ok,感谢
