### ISSUE TITLE
关于.html使用不了的问题

### ISSUE THREAD

**Issue by Xinrong-X** [jaluik/dot-log#2]
你好可以解决.html文件内的script标签不能使用的问题吗

**Comment by jaluik** [comment]
可以支持的，下个版本更新

**Comment by Machine-gun-dadadadadadada** [comment]
关于 .log 与 .clg 高度重合的问题 ，例如：我想输出一个变量i到控制台时，并不想在前面输出i的描述信息，而 .log 与 .clg 他们两个的功能都是类似的，我觉得 .log 只做输出就好了，望作者采纳
![3f4a003c1c3d2157134d658e72b59a4](https://user-images.githubusercontent.com/83322025/175764487-db7578c4-93cf-4942-9646-9ed5f2565046.png)

**Comment by jaluik** [comment]
已发布0.1.4版本  支持html文件了
