### ISSUE TITLE
关于 .log 与 .clg 重合问题

### ISSUE THREAD

**Issue by Xinrong-X** [jaluik/dot-log#3]

**Comment by Xinrong-X** [comment]
关于 .log 与 .clg 高度重合的问题 ，例如：我想输出一个变量i到控制台时，并不想在前面输出i的描述信息，而 .log 与 .clg 他们两个的功能都是类似的，我觉得 .log 只做输出就好了，望作者采纳
![3f4a003c1c3d2157134d658e72b59a4](https://user-images.githubusercontent.com/83322025/175764600-8e6bc208-7dc1-4042-bf0c-a1ebed4143f7.png)

**Comment by jaluik** [comment]
这个我现在加了配置项， 你可以用这个配置来实现你的需求

```json

  "dotLog.config": [
    {
      "trigger": "log",
      "description": "quick console.log result",
      "format": "console.log",
      "hideName": true
    },
    {
      "trigger": "clg",
      "description": "quick console.log result",
      "format": "console.log",
    }
  ],
```
