### ISSUE TITLE
format能否支持更高自由度的配置

### ISSUE THREAD

**Issue by Neco86** [jaluik/dot-log#5]
// 例如以下的例子
// format: console.log($1)
test.log  => console.log(test)

// format: console.log("$1", $1)
test.log => console.log("test", test)

// format: console.log($1, '$1')
test.log => console.log(test, 'test')

// format: console.log(\`%c$1\`, "color:red")
test.log => console.log(\`%c${test}\`, "color:red")

**Comment by jaluik** [comment]
你说的这个问题我考虑过，但是这样高的自由度是有问题的。

- 单引号、双引号的问题
- 想打印的只有字符串，format 无法自适应 

比如，我想打印 "xxx".length, 目前是可以直接输出为 console.log('"xxx".length', "xxx".length) , 如果你配置console.log("$1", $1)， 引号不好自适应

再比如： 如果你配置console.log("$1", $1)   那么 "xxx".log 显示就是有问题的

**Comment by jaluik** [comment]
现在的配置已经可以满足绝大部分需求了
