### ISSUE TITLE
关于.log不能输出带有空格的代码段

### ISSUE THREAD

**Issue by Xinrong-X** [jaluik/dot-log#6]
使用.log进行输出，例如：typeof result （却只会输出result，而把typeof 忽略了）

**Comment by jaluik** [comment]
目前不支持输出的内容间有空格

因为有空格的语句具有二意性，无法判断你是想输出整个语句 还是最近的变量

**Comment by Machine-gun-dadadadadadada** [comment]
可以加一项配置可供选择

**Comment by Machine-gun-dadadadadadada** [comment]
我觉得这个有点歧义，如果说要输出单个语句，完全可以把这单个语句换进行输出，这也符合程序员的习惯（个人意见）

**Comment by Xinrong-X** [comment]
我觉得这个有点歧义，如果说要输出单个语句，完全可以把这单个语句换进行输出，这也符合程序员的习惯（个人意见）
建议：可以加个配置项

**Comment by jaluik** [comment]
那怎么适配`const  a = 3  a.log` 这种情况呢

**Comment by Xinrong-X** [comment]
换行
